# Generated by Django 4.2.10 on 2024-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_rename_title_newsletter_subject"),
        ("alert", "0002_alert_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="papers",
            field=models.ManyToManyField(related_name="alerts", to="newsletter.paper"),
        ),
    ]
