# Generated by Django 4.2.10 on 2024-04-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_customer_id_user_is_paid_subscriber_user_plan_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="snoozed",
        ),
    ]
