# Generated by Django 4.2.10 on 2024-04-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="schedule",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("BI_WEEKLY", "Bi Weekly"),
                    ("TRI_WEEKLY", "Tri Weekly"),
                ],
                default="WEEKLY",
                max_length=15,
            ),
        ),
    ]
