# Generated by Django 4.2.10 on 2024-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="paper_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
