# Generated by Django 4.2.10 on 2024-04-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paper",
            options={},
        ),
        migrations.RemoveField(
            model_name="paper",
            name="paper_number",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="published_at",
        ),
    ]
