# Generated by Django 5.0 on 2023-12-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='sent_at',
            new_name='last_sent',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='topic',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(to='newsletter.subscriber'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='topic',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='newsletter.papertopic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='topics',
            field=models.ManyToManyField(related_name='papers', to='newsletter.papertopic'),
        ),
        migrations.AlterField(
            model_name='papertopic',
            name='abbrv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PersonalNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='newsletter.subscriber')),
            ],
        ),
    ]
