# Generated by Django 5.0.6 on 2024-06-22 16:48

from django.db import migrations


quantitative_biology_categories = [
    {'name': 'Biomolecules', 'abbrv': 'q-bio.BM'}, 
    {'name': 'Cell Behavior', 'abbrv': 'q-bio.CB'}, 
    {'name': 'Genomics', 'abbrv': 'q-bio.GN'}, 
    {'name': 'Molecular Networks', 'abbrv': 'q-bio.MN'}, 
    {'name': 'Neurons and Cognition', 'abbrv': 'q-bio.NC'}, 
    {'name': 'Other Quantitative Biology', 'abbrv': 'q-bio.OT'}, 
    {'name': 'Populations and Evolution', 'abbrv': 'q-bio.PE'}, 
    {'name': 'Quantitative Methods', 'abbrv': 'q-bio.QM'}, 
    {'name': 'Subcellular Processes', 'abbrv': 'q-bio.SC'}, 
    {'name': 'Tissues and Organs', 'abbrv': 'q-bio.TO'}
]


def create_categories(apps, schema_editor):
    Category = apps.get_model("newsletter", "Category")
    categories = [
        Category()
    ]
    for category in quantitative_biology_categories:



class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
