# Generated by Django 4.2.10 on 2024-04-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_paper_options_remove_paper_paper_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="subjects",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="authors",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="paper",
            name="main_page",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="pdf_url",
            field=models.URLField(unique=True),
        ),
    ]
