# Generated by Django 4.2.10 on 2024-04-05 08:37

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_paper_paper_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertopic",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="newsletter.papertopic",
            ),
        ),
    ]
