# Generated by Django 5.0 on 2023-12-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_sent_at_newsletter_last_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnewsletter',
            name='papers',
            field=models.ManyToManyField(to='newsletter.paper'),
        ),
    ]
