# Generated by Django 4.2.10 on 2024-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_auto_20240622_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="similar_papers",
            field=models.ManyToManyField(to="newsletter.paper"),
        ),
    ]
