# Generated by Django 5.0 on 2023-12-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_personalnewsletter_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
