# Generated by Django 4.2.10 on 2024-04-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_papertopic_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="google_scholar",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="semantic_scholar",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="tex_source",
            field=models.URLField(null=True, unique=True),
        ),
    ]
