# Generated by Django 5.0 on 2024-01-01 13:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_paper_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribers', models.ManyToManyField(related_name='subscriptions', to='newsletter.subscriber')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletter.papertopic')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='last_sent',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='Predefined title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='newsletter.papertopic'),
        ),
        migrations.DeleteModel(
            name='PersonalNewsletter',
        ),
    ]
