# Generated by Django 4.2.10 on 2024-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_paper_google_scholar_paper_semantic_scholar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertopic",
            name="abbrv",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
