# Generated by Django 4.2.10 on 2024-04-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_alter_papertopic_abbrv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="title",
            new_name="subject",
        ),
    ]
