# Generated by Django 4.2.10 on 2024-04-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0003_alter_alert_papers"),
        ("newsletter", "0006_rename_title_newsletter_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="alert",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="alert.alert",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="newsletter.papertopic",
            ),
        ),
    ]
