# Generated by Django 4.2.10 on 2024-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_newsletter_alert_alter_newsletter_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
