# Generated by Django 4.2.10 on 2024-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0008_newsletter_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
