# Generated by Django 4.2.10 on 2024-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0009_alter_newsletter_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="slug",
            field=models.SlugField(),
        ),
    ]
