# Generated by Django 4.2.10 on 2024-04-23 00:16

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0010_alter_newsletter_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="PaperChunks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk", models.TextField()),
                ("token_count", models.IntegerField(null=True)),
                ("embedding", pgvector.django.VectorField(dimensions=384)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="newsletter.paper",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
