# Generated by Django 4.2.10 on 2024-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0011_newsletter_updated_at_alter_newsletter_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperchunks",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
