name: wednesdaypipeline

on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        # Feel free to change this cron schedule
        # Currently its scheduled for 00:10, only on Wed
        - cron: "10 0 * * 3"
    # workflow_Dispatch: {}

jobs:
    send_wednesday_newsletter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.x
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Send wednesday newsletters
              run: |
                python src/manage.py send_newsletter TRI_WEEKLY
              env:
                DEBUG: ${{ secrets.DEBUG }}
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
                STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
                STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
                DOMAIN_URL: ${{ secrets.DOMAIN_URL }}
                GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
                EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
